### ISSUE TITLE
ValueError: `validation_steps=None` is only valid for a generator based on the `keras.utils.Sequence` class. Please specify `validation_steps` or use the `keras.utils.Sequence` class.

### ISSUE THREAD

**Issue by zyyhl** [pierluigiferrari/ssd_keras#102]
ValueError                                Traceback (most recent call last)
<ipython-input-22-9e051c003cc7> in <module>()
     10                               validation_data=val_generator,
     11                               validation_steps=ceil(val_dataset_size/batch_size),
---> 12                               initial_epoch=initial_epoch)

~/anaconda2/envs/py3/lib/python3.5/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name +
     90                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~/anaconda2/envs/py3/lib/python3.5/site-packages/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   2105         if (val_gen and not isinstance(validation_data, Sequence) and
   2106                 not validation_steps):
-> 2107             raise ValueError('`validation_steps=None` is only valid for a'
   2108                              ' generator based on the `keras.utils.Sequence`'
   2109                              ' class. Please specify `validation_steps` or use'

ValueError: `validation_steps=None` is only valid for a generator based on the `keras.utils.Sequence` class. Please specify `validation_steps` or use the `keras.utils.Sequence` class.
I found an error using ssd-training，thanks

**Comment by pierluigiferrari** [comment]
1. When you post an issue, please format code as code, otherwise it's a pain in the ass to read.
2. You need to provide more information than just the error message traceback: What versions of Keras and TensorFlow are you on, what operating system, etc.
3. I cannot reproduce your error on the latest master with Keras 2.1.3 and TensorFlow 1.4.1. As the traceback shows, it is `validation_steps=ceil(val_dataset_size/batch_size)`, so clearly it is not `validation_steps=None`, so this error doesn't make any sense to me.

**Comment by zyyhl** [comment]
@pierluigiferrari  I solved the problem, thank you

**Comment by zyyhl** [comment]
@IshwaryaJayakumar  I did not set up a validation set and a test set at the time, so I will report an error and add a validation set and test set to resolve the problem.

**Comment by Joeng22** [comment]
Hi,
You need to add validation_steps in fit_generator() function.

eg :  modeltemp.fit_generator(
        train_generator,
        steps_per_epoch = nb_train_samples,
        epochs = epochs,
        validation_steps=20,
        validation_data = validation_generator,
        callbacks=[checkpoint, early,plot_losses])

**Comment by yoyojacky** [comment]
@Joeng22  
still not work...

**Comment by emanuelevivoli** [comment]
I had the same error, and I came out of this after modified the validation_steps. 
Maybe **it cannot be too low**.

**Comment by asetkn** [comment]
Hi,

I had the same error. My validation_steps were set to:
`validation_steps=nb_validation_samples // batch_size`
Turns out my `nb_validation_samples ` were less than `batch_size`

**Comment by qinhuangdaoStation** [comment]
model.fit_generator(generate_train,
                        steps_per_epoch=steps_per_epoch,
                        epochs=epochs,
                        verbose=1,
                        validation_data=generate_test,
                        validation_steps=validation_steps,
                        shuffle=True,
                        callbacks=callbacks)
I had added the 'validation_steps=validation_steps', but it still noted that like this:
ValueError: `validation_steps=None` is only valid for a generator based on the `keras.utils.Sequence` class. Please specify `validation_steps` or use the `keras.utils.Sequence` class.
How colude I do? My Keras Version is 2.2.4, and Tensorflow is 1.13.1.

**Comment by qinhuangdaoStation** [comment]
Sorry , I see.
We can trace to the ../keras/engine/training_generator.py， there are the source code, like this. 
So, we just modify the condition is ok. I don't have the tensorflow.keras.Model, I just use the Keras.Model.Sequential. Thanks!

`val_gen = (hasattr(validation_data, 'next') or
               hasattr(validation_data, '__next__') or
               isinstance(validation_data, Sequence))
    if (val_gen and not isinstance(validation_data, Sequence) and
            not validation_steps):
        raise ValueError('`validation_steps=None` is only valid for a'
                         ' generator based on the `keras.utils.Sequence`'
                         ' class. Please specify `validation_steps` or use'
                         ' the `keras.utils.Sequence` class.')`

**Comment by RAHULPRRAHUL** [comment]
hey 
I was getting same error and its because of correct value for steps_per_epoch. 

model.fit_generator(datagen.flow(x_train, y_train, batch_size=32),
                    steps_per_epoch=len(x_train) / 32, epochs=epochs)

for more information check the link:
https://keras.io/preprocessing/image/

**Comment by Digital2Slave** [comment]
@RAHULPRRAHUL thanks!

**Comment by TD91988** [comment]
this is my code what i need to change to avoid below errors 
Code - 
import os
import pandas as pd
import numpy as np
#import Keras
import sklearn
import matplotlib.pyplot as plt
from imutils import paths
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from keras.applications import VGG19
from keras.preprocessing.image import ImageDataGenerator
from keras.optimizers import SGD
from keras.models import Model
from keras.layers import Dropout, Flatten, Dense, GlobalAveragePooling2D
from keras.callbacks import EarlyStopping
from keras.utils.data_utils import Sequence
#from keras.utils.Sequence

os.chdir("D:/ADMTest/chest_xray/")

# defining constants and variables
img_width, img_height = 128, 128
train_data_dir = "data/train"
validation_data_dir = "data/val"
test_data_dir = "data/test"
NB = 2
BS = 64
EPOCHS = 2


# creating train, validation and test data generators
TRAIN = len(list(paths.list_images(train_data_dir)))
VAL = len(list(paths.list_images(validation_data_dir)))
TEST = len(list(paths.list_images(test_data_dir)))

trainAug = ImageDataGenerator(rescale = 1./255,
                    fill_mode = "nearest")

valAug = ImageDataGenerator(rescale = 1./255,
                            fill_mode = "nearest")

trainGen = trainAug.flow_from_directory(
                    train_data_dir,
                    target_size = (img_height, img_width),
                    batch_size = BS,
                    shuffle = True,
                    class_mode = "categorical")

valGen = valAug.flow_from_directory(
                    validation_data_dir,
                    target_size = (img_height, img_width),
                    batch_size = BS,
                    shuffle = False,
                    class_mode = "categorical")

testGen = valAug.flow_from_directory(
                    test_data_dir,
                    target_size = (img_height, img_width),
                    batch_size = BS,
                    shuffle = False,
                    class_mode = "categorical")


# loading pre-trained model, training additional features and saving model
base_model = VGG19(weights = "imagenet", include_top=False,
                   input_shape = (img_width, img_height, 3))
x = base_model.output
x = Flatten()(x)
x = Dense(1024, activation = "relu")(x)
x = Dropout(0.4)(x)
x = Dense(256, activation = "relu")(x)
x = Dropout(0.2)(x)
preds = Dense(NB, activation = "softmax")(x)

model = Model(input = base_model.input, output = preds)

for i,layer in enumerate(model.layers):
    print(i,layer.name)

for layer in model.layers[:16]:
    layer.trainable=False
for layer in model.layers[16:]:
    layer.trainable=True

model.summary()

early = EarlyStopping(monitor = 'val_acc', min_delta = 0,
                      patience = 10, verbose= 1 , mode = 'auto')

model.compile(loss = "binary_crossentropy",
                    optimizer = SGD(lr=0.001, momentum=0.9),
                    metrics=["accuracy"])

H = model.fit_generator(
        trainGen,
        epochs = EPOCHS,
        #steps_per_epoch = len(),
        steps_per_epoch = TRAIN // BS,
        validation_data = valGen,
        validation_steps = VAL // BS,
        callbacks = [early])

model.save('model.h5')


# generating predictions using model
testGen.reset()
predictions = model.predict_generator(testGen, steps = (TEST // BS) + 1)
predictions = np.argmax(predictions, axis=1)

print("Test set accuracy: " +
      str(accuracy_score(testGen.classes, predictions, normalize=True) * 100)
      + "%")

print(classification_report(testGen.classes, predictions,
                            target_names=testGen.class_indices.keys()))


# plotting training data
plt.style.use("ggplot")
plt.figure()
plt.plot(np.arange(0, EPOCHS), H.history["loss"], label="train_loss")
plt.plot(np.arange(0, EPOCHS), H.history["val_loss"], label="val_loss")
plt.plot(np.arange(0, EPOCHS), H.history["acc"], label="train_acc")
plt.plot(np.arange(0, EPOCHS), H.history["val_acc"], label="val_acc")
plt.title("Training Loss and Accuracy on Dataset")
plt.xlabel("Epoch #")
plt.ylabel("Loss/Accuracy")
plt.legend(loc="lower left")
plt.savefig("plot.jpg")


Error log -
_________________________________________________________________
WARNING:tensorflow:From C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Traceback (most recent call last):
  File "E:\Sem2\ADM\train.py", line 96, in <module>
    callbacks = [early])
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=0)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training_generator.py", line 68, in fit_generator
    raise ValueError('`validation_steps=20` is only valid for a'
ValueError: `validation_steps=20` is only valid for a generator based on the `keras.utils.Sequence` class. Please specify `validation_steps` or use the `keras.utils.Sequence` class.
[Finished in 9.142s]

**Comment by OZLEM2020** [comment]
The problem was solved  increasing the data set
