### ISSUE TITLE
Error running ssd300_evaluation_Pascal_VOC 

### ISSUE THREAD

**Issue by tluth** [pierluigiferrari/ssd_keras#108]
I'm trying to use the evaluation code on an SSD512 model I trained using your repo. I've got the latest repo. Haven't touched any of the other files. 

The only changes I made to the code other than changing file paths was to swap out the ssd300 model for ssd512, and obviously adjust scales, aspect_ratios_per_layer, steps, etc. following your suggested values for those variables. 

I'm using a dataset of one class. The images, annotations and imageset files all follow the same format as what was used in training and inference successfully. 

I'm getting this invalid literal for int() with base 10 error in the average precision evaluator. See below:

```
Using TensorFlow backend.
2018-04-24 21:07:52.705394: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
test.txt:   0%|          | 0/100 [00:00<?, ?it/s]
test.txt:  68%|######8   | 68/100 [00:00<00:00, 677.94it/s]
test.txt: 100%|##########| 100/100 [00:00<00:00, 711.41it/s]
Number of images in the evaluation dataset: 100

Traceback (most recent call last):
  File "/ssd_keras-master/tl_eval_complete.py", line 105, in <module>
    verbose=True)
  File "/ssd_keras-master/eval_utils/average_precision_evaluator.py", line 193, in __call__
    ret=False)
  File "/ssd_keras-master/eval_utils/average_precision_evaluator.py", line 394, in predict_on_dataset
    image_id = int(batch_image_ids[k])
ValueError: invalid literal for int() with base 10: 'Test1'
  0%|          | 0/13 [00:00<?, ?it/s]
Producing predictions batch-wise:   0%|          | 0/13 [00:00<?, ?it/s]
[Finished in 23.527s]
```

**Comment by tluth** [comment]
Okay, so I'm reopening this just to let you know the issue seems to come from having image/annotation file names which aren't ints.. 

I ran it again after trying with new file names and got this result: 

```
Traceback (most recent call last):
  File "/Users/tomlutherborrow/Downloads/ssd_keras-master/tl_eval_complete.py", line 125, in <module>
    cells[i, j].plot(recalls[n*i+j+1], precisions[n*i+j+1], color='blue', linewidth=1.0)
IndexError: list index out of range
[Finished in 254.842s]
```

still, it printed the mAP which was all I wanted to see. I just wanted to bring your attention to this.

**Comment by tluth** [comment]
Another fairly minor thing I wanted to bring up is the discrepancy between the 'mode' and 'model_mode' variable names. Would it not be easier to use the one variable name?

**Comment by pierluigiferrari** [comment]
Yes, what you are seeing is expected behavior. I agree it's not great though. The way the evaluator is set up right now, the image IDs must be convertible to integers. I hadn't considered your case yet because the names of Pascal VOC images consist of digits only and it makes things more convenient in the evaluator internally, but I realize that this isn't optimal. I'll look into chaging this so that it works with arbitrary (non-number) image names.

> Another fairly minor thing I wanted to bring up is the discrepancy between the 'mode' and 'model_mode' variable names. Would it not be easier to use the one variable name?

Yeah, that's not ideal. The thing is that calling it `model_mode` in the function that build the model (`ssd_300()`) is unnecessary because of course the `mode` refers to the mode of the model. On the other hand, calling it just `mode` in the evaluator wouldn't be ideal because that argument name wouldn't indicate that it is about the mode of the model. In its next version, the evaluator will also have another mode argument to select between VOC pre-2010 and post-2010 average precision computation styles. I might have to find better names for these arguments altogether.

**Comment by pierluigiferrari** [comment]
I pushed a new version of the evaluator that is no longer restricted to digit-only image names. Give it a try and let me know if it works now.

**Comment by tluth** [comment]
Yep works now. Cheers. 

It still requires some adjustments to the plotting stage if you're dealing with a different number of classes, but no biggie. 

Thanks again.

**Comment by pierluigiferrari** [comment]
Great. Yeah, to be honest, I've never taken time to figure out how the `figsize` parameter really works. In case you can tell me how to parameterize the `figsize` depending on the number of classes so that it works for the general case, let me know 🙂

**Comment by Yaoyuanzhou** [comment]
@tluth hello，I meet this problem when I try to run ssd300_evaluation.ipynb. Can you help me? thank you!

No predictions for class 1/21
No predictions for class 2/21
No predictions for class 3/21
No predictions for class 4/21
No predictions for class 5/21
No predictions for class 6/21
No predictions for class 7/21
No predictions for class 8/21
No predictions for class 9/21
No predictions for class 10/21
No predictions for class 11/21
No predictions for class 12/21
No predictions for class 13/21
No predictions for class 14/21
No predictions for class 15/21
No predictions for class 16/21
No predictions for class 17/21
No predictions for class 18/21
No predictions for class 19/21
No predictions for class 20/21
No predictions for class 21/21
Computing precisions and recalls, class 1/21
Traceback (most recent call last):
  File "ssd300_evaluation.py", line 188, in <module>
    verbose=True)
  File "C:\Users\Mr_Yao\Desktop\SSD\ssd_keras-master\eval_utils\average_precision_evaluator.py", line 226, in __call__
    self.compute_precision_recall(verbose=verbose, ret=False)
  File "C:\Users\Mr_Yao\Desktop\SSD\ssd_keras-master\eval_utils\average_precision_evaluator.py", line 767, in compute_precision_recall
    tp = self.cumulative_true_positives[class_id]
IndexError: list index out of range
