### ISSUE TITLE
TypeError: l2_normalize() got an unexpected keyword argument 'axis'

### ISSUE THREAD

**Issue by parvez2307** [pierluigiferrari/ssd_keras#120]
from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/home/pcadmin/aakash/ssd_keras-master/data_generator/object_detection_2d_data_generator.py:43: UserWarning: 'BeautifulSoup' module is missing. The XML-parser will be unavailable.
  warnings.warn("'BeautifulSoup' module is missing. The XML-parser will be unavailable.")
Traceback (most recent call last):
  File "ssd300_training.py", line 63, in <module>
    swap_channels=swap_channels)
  File "/home/pcadmin/aakash/ssd_keras-master/models/keras_ssd300.py", line 316, in ssd_300
    conv4_3_norm = L2Normalization(gamma_init=20, name='conv4_3_norm')(conv4_3)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/pcadmin/aakash/ssd_keras-master/keras_layers/keras_layer_L2Normalization.py", line 62, in call
    output = K.l2_normalize(x, self.axis)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 3151, in l2_normalize
    return tf.nn.l2_normalize(x, axis=axis)
TypeError: l2_normalize() got an unexpected keyword argument 'axis'

versions:
python: 2.7.4
tensorflow : 1.4.0
keras: 2.1.5

**Comment by pierluigiferrari** [comment]
You didn't search the closed issues, this exact issue has been solved before.
