### ISSUE TITLE
(Weight Sampling) IndexError: index 15 is out of bounds for axis 0 with size 3

### ISSUE THREAD

**Issue by ecophy** [pierluigiferrari/ssd_keras#122]
Thanks a lot for great information here ^_^ I am doing Pascal VOC weight sampling with the classes of interest being [ 0,  5(bottle),15(person)]. I ran [01]-[08] of weight_sampling_tutorial.ipynb then I ran [01]-[08] of ssd300_training.ipynb (with a slight modification of using parse_csv for input_format=['image_name', 'xmin', 'xmax', 'ymin', 'ymax', 'class_id']). I set n_classes (# of positive classes) to be 2 as in the tutorial. Then, I got the following error message. How can I fix the error? I really appreciate your kind support :) 

Traceback (most recent call last):

  File "<ipython-input-5-a52300610a34>", line 53, in <module>
    initial_epoch=initial_epoch)

  File "C:\Users\Administrator\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\Administrator\Anaconda3\lib\site-packages\keras\engine\training.py", line 2192, in fit_generator
    generator_output = next(output_generator)

  File "C:\Users\Administrator\Anaconda3\lib\site-packages\keras\utils\data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)

  File "C:\Users\Administrator\Anaconda3\lib\site-packages\six.py", line 686, in reraise
    raise value

  File "C:\Users\Administrator\Anaconda3\lib\site-packages\keras\utils\data_utils.py", line 658, in _data_generator_task
    generator_output = next(self._generator)

  File "<ipython-input-1-9265fa38816e>", line 4786, in generate
    batch_y_encoded = label_encoder(batch_y, diagnostics=False)

  File "<ipython-input-1-9265fa38816e>", line 2480, in __call__
    classes_one_hot = class_vectors[labels[:, class_id].astype(np.int)] # The one-hot class IDs for the ground truth boxes of this batch item

IndexError: index 15 is out of bounds for axis 0 with size 3

**Comment by pierluigiferrari** [comment]
It seems that the "person" objects in your dataset have class ID 15. Since you built a model with 2 positive classes, the model expects only 1 and 2 as ground truth class IDs.

In general, if you have `k` positive classes, you must ensure that the objects in your ground truth are labeled with class IDs in the set {1, ..., k}.

**Comment by ecophy** [comment]
Thanks a lot for your kind support ^_^ I followed your suggestion and the code worked well :) Please, have a nice day!

**Comment by pierluigiferrari** [comment]
You're welcome.
