### ISSUE TITLE
Getting empty batch_filenames in object_detection_2d_data_generator.py after first epoch

### ISSUE THREAD

**Issue by giorkarag** [pierluigiferrari/ssd_keras#184]
Hello and thank you very much for all the implementations available on this repository.
I am trying to train the SSD512 model on my dataset based on the ssd300_training.ipynb guidelines you provide. I only modified the necessary stuff on this guide (aspect_ratios and predictor_sizes for instance). I manage to start training but at the end of the first epoch I get the following error:

Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/railwaydata//my_scripts/ssd/train_ssd_512.py", line 391, in <module>
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training_generator.py", line 233, in fit_generator
    workers=0)
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1472, in evaluate_generator
    verbose=verbose)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training_generator.py", line 329, in evaluate_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py", line 709, in get
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py", line 685, in get
    inputs = self.queue.get(block=True).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py", line 626, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])
  File "/mnt/batch/tasks/shared/LS_root/mounts/railwaydata/my_scripts/ssd/data_generator/object_detection_2d_data_generator.py", line 1128, in generate
    batch_filenames.pop(j)
AttributeError: 'NoneType' object has no attribute 'pop'

I really struggle three days now to detect the root of this error but no clue why the batch_filenames is empty.

The problem is that self.filenames is None while self.hdf5_dataset is not None in lines 1006-1012 of object_detection_2d_data_generator.py. 

I am using the latest version of this repository. Running on Azure Batch AI Cluster with:
Canonical UbuntuServer 16.04-LTS
keras-2.2.3
tensorflow:1.8.0
K80 GPU

My dataset consists of 100K 512X512 .jpg images. I introduce the annotations using parse_xml and 
I create .h5 files of the dataset as suggested. For training, I reduced the batch size to 16 because of memory issues and Adam optimizer instead of SGD.

Please let me know if you think I am doing something wrong or if I can provide any further details.

**Comment by giorkarag** [comment]
Just to keep it active.

**Comment by giorkarag** [comment]
Update: When I load all the data into the model, training starts normally without the above problem. However, in this case, every few epochs it stops training in the middle of some epoch and starts loading the images again (which is a very long process). Does any of ever faced the same issue? Do you know why is this happening?

**Comment by JosephPai** [comment]
Hi, I've encountered the same problem.

> batch_filenames.pop(j)
AttributeError: 'NoneType' object has no attribute 'pop'

I guess you've run the code with reading HDF5 file.
**NOTE: when you create the HDF5 file, the filenames is not included !**

So the solution is:
change the `line 1122` of `data_generator/object_detection_2d_data_generator.py`
from
`batch_filenames.pop(j)`

to

`if not batch_filenames.empty():`
`batch_filenames.pop(j)`

That's it !
