### ISSUE TITLE
SSD300 train throw gradients error

### ISSUE THREAD

**Issue by amichayfeldman** [pierluigiferrari/ssd_keras#205]
Hi

I tried used the SSD300 model, subsampled the weights to players detection (just 2 labels : persons and background) and train on my own dataset.

When i run model.fit_generator function, i got error :+1: `

`An operation has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.`

I tried search and solved in the functions definition, but didn't success with that.

I uploaded my temp code to : [https://github.com/amichayfeldman/SSD/blob/master/temp](url)

Any help for that?
Thanks

`

**Comment by amichayfeldman** [comment]
I still have this problem and didnt succeed solve it.

**Comment by amichayfeldman** [comment]
Hi
I also tried to train ssd512, and got same errors:
```
Traceback (most recent call last):

  File "<ipython-input-154-7d9da5d0e1a4>", line 11, in <module>
    initial_epoch=initial_epoch)

  File "C:\Users\yuvalm\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\yuvalm\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)

  File "C:\Users\yuvalm\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\training_generator.py", line 40, in fit_generator
    model._make_train_function()

  File "C:\Users\yuvalm\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\training.py", line 509, in _make_train_function
    loss=self.total_loss)

  File "C:\Users\yuvalm\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\yuvalm\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\optimizers.py", line 475, in get_updates
    grads = self.get_gradients(loss, params)

  File "C:\Users\yuvalm\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\optimizers.py", line 91, in get_gradients
    raise ValueError('An operation has `None` for gradient. '

ValueError: An operation has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.
```

I uploaded my code to : [https://github.com/amichayfeldman/SSD/blob/master/test2.py](url)

So i guess this issue is caused by internal function or something similiar.

**Comment by jessiffmm** [comment]
@amichayfeldman Did you resolve your problem?
I have the same problem if I use inference mode and I try to do fit_generator.

**Comment by amichayfeldman** [comment]
First of all' try change 'inference mode' to 'training'. Secondly, i iterate over the layers and define which layers i want to train. Somehow this "solved" my issue (i assume that one of the first layers that i finally didnt train caused to the issue)

**Comment by JoaoGranzotti** [comment]
I'm having the same problem, did you manage to find a solution, could you share the code? I need to make this network work for important college work.
