### ISSUE TITLE
ValueError: Tensor("training/Adam/Const:0", shape=(), dtype=float32) must be from the same graph as Tensor("sub:0", shape=(), dtype=float32).

### ISSUE THREAD

**Issue by TianwenZhang0825** [pierluigiferrari/ssd_keras#283]
Traceback (most recent call last):
  File "ssd7_train.py", line 251, in <module>
    initial_epoch    = initial_epoch)
  File "C:\017-Anaconda3\envs\n4-keras-faster-rcnn-gpu\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\017-Anaconda3\envs\n4-keras-faster-rcnn-gpu\lib\site-packages\keras\engine\training.py", line 2080, in fit_generator
    self._make_train_function()
  File "C:\017-Anaconda3\envs\n4-keras-faster-rcnn-gpu\lib\site-packages\keras\engine\training.py", line 992, in _make_train_function
    loss=self.total_loss)
  File "C:\017-Anaconda3\envs\n4-keras-faster-rcnn-gpu\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\017-Anaconda3\envs\n4-keras-faster-rcnn-gpu\lib\site-packages\keras\optimizers.py", line 454, in get_updates
    lr_t = lr * (K.sqrt(1. - K.pow(self.beta_2, t)) /
  File "C:\017-Anaconda3\envs\n4-keras-faster-rcnn-gpu\lib\site-packages\keras\backend\tensorflow_backend.py", line 1465, in sqrt
    x = tf.clip_by_value(x, zero, inf)
  File "C:\017-Anaconda3\envs\n4-keras-faster-rcnn-gpu\lib\site-packages\tensorflow\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "C:\017-Anaconda3\envs\n4-keras-faster-rcnn-gpu\lib\site-packages\tensorflow\python\ops\clip_ops.py", line 67, in clip_by_value
    [t, clip_value_min, clip_value_max]) as name:
  File "C:\017-Anaconda3\envs\n4-keras-faster-rcnn-gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 6508, in __enter__
    g = _get_graph_from_inputs(self._values)
  File "C:\017-Anaconda3\envs\n4-keras-faster-rcnn-gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 6135, in _get_graph_from_inputs
    _assert_same_graph(original_graph_element, graph_element)
  File "C:\017-Anaconda3\envs\n4-keras-faster-rcnn-gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 6071, in _assert_same_graph
    (item, original_item))
ValueError: Tensor("training/Adam/Const:0", shape=(), dtype=float32) must be from the same graph as Tensor("sub:0", shape=(), dtype=float32).

**Comment by ghost** [comment]
Hello, I have same issue (ValueError: Tensor("training/Adam/Const:0", shape=(), dtype=float32)......) and tried tensorflow 1.13-2.0 and with keras 2.0-2.3 and no luck. Also tried to changed K. Clear_session() to keras.backend.clear_session() and still have same error. Can anyone help ?
Thanks
