### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Index out of range using input dim 0; input has only 0 dims 	 [[{{node loss/efficientnet-b0_loss/strided_slice_2}}]]

### ISSUE THREAD

**Issue by diefish2** [pierluigiferrari/ssd_keras#323]
2020-01-14 11:19:21.012255: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at strided_slice_op.cc:108 : Invalid argument: Index out of range using input dim 0; input has only 0 dims
2020-01-14 11:19:21.012262: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at strided_slice_op.cc:108 : Invalid argument: Index out of range using input dim 0; input has only 0 dims
2020-01-14 11:19:21.012287: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at strided_slice_op.cc:108 : Invalid argument: Index out of range using input dim 0; input has only 0 dims
2020-01-14 11:19:21.012255: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at strided_slice_op.cc:108 : Invalid argument: Index out of range using input dim 0; input has only 0 dims
Traceback (most recent call last):
  File "keras_efficient_transfer_learning_2.py", line 319, in <module>
    verbose = 0
  File "/home/timmy/anaconda3/envs/tf_gpu_0/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 793, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/timmy/anaconda3/envs/tf_gpu_0/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_generator.py", line 604, in fit
    steps_name='steps_per_epoch')
  File "/home/timmy/anaconda3/envs/tf_gpu_0/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_generator.py", line 265, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "/home/timmy/anaconda3/envs/tf_gpu_0/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1084, in train_on_batch
    outputs = self.train_function(ins)  # pylint: disable=not-callable
  File "/home/timmy/anaconda3/envs/tf_gpu_0/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py", line 3567, in __call__
    run_metadata=self.run_metadata)
  File "/home/timmy/anaconda3/envs/tf_gpu_0/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1474, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Index out of range using input dim 0; input has only 0 dims
	 [[{{node loss/efficientnet-b0_loss/strided_slice_2}}]]

**Comment by diefish2** [comment]
Does anyone see this error before?
