### ISSUE TITLE
Error while trying to use blazy

### ISSUE THREAD

**Issue by trapkeed** [pierluigiferrari/ssd_keras#335]
Traceback (most recent call last):
  File "blazy.py", line 60, in <module>
    soup =  BeautifulSoup(data, 'lxml') #Pareses the response with beuatiful soup
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/bs4/__init__.py", line 228, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by trapkeed** [comment]
☝️☝️I am using Android 9
