### ISSUE TITLE
IndexError: index 1 is out of bounds for axis 0 with size 1

### ISSUE THREAD

**Issue by roaur** [pierluigiferrari/ssd_keras#45]
Hello!

Thank you for all the work you've done to port SSD to Keras!

I'm trying to train a subset of annotated data from MS COCO using ssd7_training.ipynb with two classes (background and the one feature I'm interested in) and I've largely left your parameters the way they are in the repo except for file and directory paths. I've made it to `4. Run the training` without a hitch (`n_train_samples` and `n_val_samples` are giving the correct number of images I have in my directories). 

Here is a sample of my training label data I've tried to mimic the labels.csv example in your Udacity training dataset:

frame | xmin | xmax | ymin | ymax | class_id
-- | -- | -- | -- | -- | --
000000246963.jpg | 437 | 480 | 81 | 125 | 1
000000222094.jpg | 107 | 157 | 81 | 156 | 1
000000441586.jpg | 525 | 549 | 74 | 96 | 1
000000261888.jpg | 236 | 245 | 221 | 230 | 1
000000480944.jpg | 71 | 116 | 216 | 286 | 1

Thinking my data is set up correctly, I try to train it by executing what is included in ssd7_training.ipynb:
```
# TODO: Set the number of epochs to train for.
epochs = 10

history = model.fit_generator(generator = train_generator,
                              steps_per_epoch = ceil(n_train_samples/batch_size),
                              epochs = epochs,
                              callbacks = [ModelCheckpoint('ssd7_weights_epoch-{epoch:02d}_loss-{loss:.4f}.h5',
                                                           monitor='val_loss',
                                                           verbose=1,
                                                           save_best_only=True,
                                                           save_weights_only=True,
                                                           mode='auto',
                                                           period=1),
                                           EarlyStopping(monitor='val_loss',
                                                         min_delta=0.001,
                                                         patience=2),
                                           ReduceLROnPlateau(monitor='val_loss',
                                                             factor=0.5,
                                                             patience=0,
                                                             epsilon=0.001,
                                                             cooldown=0)],
                              validation_data = val_generator,
                              validation_steps = ceil(n_val_samples/batch_size))

# TODO: Set the filename (without the .h5 file extension!) under which to save the model and weights.
#       Do the same in the `ModelCheckpoint` callback above.
model_name = 'ssd7'
model.save('{}.h5'.format(model_name))
model.save_weights('{}_weights.h5'.format(model_name))

print()
print("Model saved under {}.h5".format(model_name))
print("Weights also saved separately under {}_weights.h5".format(model_name))
print()
```

But I'm experiencing the following error when I start training:

```
Epoch 1/10
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/home/roman/.conda/envs/deep-learning/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/roman/.conda/envs/deep-learning/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/roman/.conda/envs/deep-learning/lib/python3.6/site-packages/keras/utils/data_utils.py", line 568, in data_generator_task
    generator_output = next(self._generator)
  File "/home/roman/git/ssd_keras/ssd_batch_generator.py", line 984, in generate
    y_true = ssd_box_encoder.encode_y(batch_y, diagnostics) # Encode the labels into the `y_true` tensor that the cost function needs
  File "/home/roman/git/ssd_keras/ssd_box_encode_decode_utils.py", line 943, in encode_y
    y_encoded[i,best_match_index,:-8] = np.concatenate((class_vector[int(true_box[0])], true_box[1:]), axis=0) # Write the ground truth box coordinates and class to the best match anchor box position
IndexError: index 1 is out of bounds for axis 0 with size 1

---------------------------------------------------------------------
StopIteration                       Traceback (most recent call last)
<ipython-input-24-3f284dc3f325> in <module>()
     21                                                              cooldown=0)],
     22                               validation_data = val_generator,
---> 23                               validation_steps = ceil(n_val_samples/batch_size))
     24 
     25 # TODO: Set the filename (without the .h5 file extension!) under which to save the model and weights.

~/.conda/envs/deep-learning/lib/python3.6/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     85                 warnings.warn('Update your `' + object_name +
     86                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 87             return func(*args, **kwargs)
     88         wrapper._original_function = func
     89         return wrapper

~/.conda/envs/deep-learning/lib/python3.6/site-packages/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   2009                 batch_index = 0
   2010                 while steps_done < steps_per_epoch:
-> 2011                     generator_output = next(output_generator)
   2012 
   2013                     if not hasattr(generator_output, '__len__'):

StopIteration: 
```

Is this error indicative of something that I haven't correctly set up? I'm using Keras 2.0.8. I'm on commit `65c5ca572ec`

**Comment by pierluigiferrari** [comment]
My first guess would be that you set `n_classes = 1`. Note that if your dataset has `n` classes, then it must be `n_classes = n + 1`, so in your case it would be `n_classes = 2`. If that's not the problem, let me know.

**Comment by roaur** [comment]
You're right. That's what it was. And it even says so in the documentation. 

Thank you very much.

**Comment by pierluigiferrari** [comment]
It's actually kinda dumb that I made it this way and you're not the first tripping over this. People think of the number of classes as the number of positive classes, they don't think of the background class as an explicit class. I should probably change this, it would be more intuitive the other way.

Out of curiosity, did you use `pycocotools` to parse the annotation JSONs or did you write your own parser?

**Comment by roaur** [comment]
I didn't use `pycocotools` to parse the annotation JSONs. I wrote my own. How come?
