### ISSUE TITLE
ssd7 own dataset

### ISSUE THREAD

**Issue by vinodrajendran001** [pierluigiferrari/ssd_keras#54]
While using my own dataset which is in VOC format, I end up with this error while initiating the training.

Epoch 1/10

ValueErrorTraceback (most recent call last)
<ipython-input-176-dabffe9209fb> in <module>()
     21                                                              cooldown=0)],
     22                               validation_data = val_generator,
---> 23                               validation_steps = ceil(n_val_samples/batch_size))
     24 
     25 

/nfs/p4/ceusers/vinod/.venv2.7-gpu/local/lib/python2.7/site-packages/keras/legacy/interfaces.pyc in wrapper(*args, **kwargs)
     85                 warnings.warn('Update your `' + object_name +
     86                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 87             return func(*args, **kwargs)
     88         wrapper._original_function = func
     89         return wrapper

/nfs/p4/ceusers/vinod/.venv2.7-gpu/local/lib/python2.7/site-packages/keras/engine/training.pyc in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   2075                     outs = self.train_on_batch(x, y,
   2076                                                sample_weight=sample_weight,
-> 2077                                                class_weight=class_weight)
   2078 
   2079                     if not isinstance(outs, list):

/nfs/p4/ceusers/vinod/.venv2.7-gpu/local/lib/python2.7/site-packages/keras/engine/training.pyc in train_on_batch(self, x, y, sample_weight, class_weight)
   1789             sample_weight=sample_weight,
   1790             class_weight=class_weight,
-> 1791             check_batch_axis=True)
   1792         if self.uses_learning_phase and not isinstance(K.learning_phase(), int):
   1793             ins = x + y + sample_weights + [1.]

/nfs/p4/ceusers/vinod/.venv2.7-gpu/local/lib/python2.7/site-packages/keras/engine/training.pyc in _standardize_user_data(self, x, y, sample_weight, class_weight, check_batch_axis, batch_size)
   1407                                     self._feed_input_shapes,
   1408                                     check_batch_axis=False,
-> 1409                                     exception_prefix='input')
   1410         y = _standardize_input_data(y, self._feed_output_names,
   1411                                     output_shapes,

/nfs/p4/ceusers/vinod/.venv2.7-gpu/local/lib/python2.7/site-packages/keras/engine/training.pyc in _standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
    140                                  ' to have ' + str(len(shapes[i])) +
    141                                  ' dimensions, but got array with shape ' +
--> 142                                  str(array.shape))
    143             for j, (dim, ref_dim) in enumerate(zip(array.shape, shapes[i])):
    144                 if not j and not check_batch_axis:

ValueError: Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (8, 1)

**Comment by pierluigiferrari** [comment]
Note that this is a Python 3 implementation as clearly stated in the README. I've just trained an SSD7 on Pascal VOC for one epoch (using `BatchGenerator`) and was not able to reproduce your error in Python 3.

The shape of the array that the batch generator passes to `fit_generator()` indicates that you are producing empty batches. Beyond that, the information you provided is not enough to do meaningful error search.
1) Are you using `BatchGenerator`?
2) Does your dataset contain images of varying size or constant size?
3) If your dataset contains images of varying size, are you using any of the batch generator's cropping/padding/resizing options to make all images the same size? If not, then this is where your error comes from.

**Comment by vinodrajendran001** [comment]
I solved this problem by adding "convert_to_3_channels=True" in generator.

However, now while starting training I am getting this following error
```
Epoch 1/10
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Users\Vinod\AppData\Local\conda\conda\envs\tensorflow-gpu\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\Vinod\AppData\Local\conda\conda\envs\tensorflow-gpu\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Vinod\AppData\Local\conda\conda\envs\tensorflow-gpu\lib\site-packages\keras\utils\data_utils.py", line 560, in data_generator_task
    generator_output = next(self._generator)
  File "C:\Users\Vinod\Downloads\OCR\ssd_keras\ssd_batch_generator.py", line 1211, in generate
    batch_y_true = ssd_box_encoder.encode_y(batch_y, diagnostics=False) # Encode the labels into the `y_true` tensor that the SSD loss function needs.
  File "C:\Users\Vinod\Downloads\OCR\ssd_keras\ssd_box_encode_decode_utils.py", line 920, in encode_y
    for i in range(y_encode_template.shape[0]): # For each batch item...
AttributeError: 'tuple' object has no attribute 'shape'

---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
<ipython-input-20-c11959bac2a8> in <module>()
     21                                                              cooldown=0)],
     22                               validation_data = val_generator,
---> 23                               validation_steps = ceil(n_val_samples/batch_size))
     24 
     25 

~\AppData\Local\conda\conda\envs\tensorflow-gpu\lib\site-packages\keras\legacy\interfaces.py in wrapper(*args, **kwargs)
     85                 warnings.warn('Update your `' + object_name +
     86                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 87             return func(*args, **kwargs)
     88         wrapper._original_function = func
     89         return wrapper

~\AppData\Local\conda\conda\envs\tensorflow-gpu\lib\site-packages\keras\engine\training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, initial_epoch)
   1807                 batch_index = 0
   1808                 while steps_done < steps_per_epoch:
-> 1809                     generator_output = next(output_generator)
   1810 
   1811                     if not hasattr(generator_output, '__len__'):

StopIteration: 
```

I am also using python3.

**Comment by pierluigiferrari** [comment]
> I solved this problem by adding "convert_to_3_channels=True" in generator.

It's strange that this option solved the original problem, because it is set to `True` by default anyway, so it was always "on" unless you manually disabled it. Does your dataset consist of  single-channel (grayscale) images or does it contain a mix of images single-channel (grayscale) and 3-channel (color) images?

> I am also using python3.

Are you certain? Because your stack trace above says you're using Python 2.7 and your new error looks like an error that is caused by the wrong Python version. It claims that `y_encode_template` in `encode_y()` is a tuple, but it is a Numpy array.

**Comment by vinodrajendran001** [comment]
Yeah previously I didn't add "convert_to_3_channels=True" because in 
SSD7 Training Tutorial.ipynb its not been used.

I am pretty sure, because in jupyter notebook the kernel used is python 3.

**Comment by pierluigiferrari** [comment]
Can you execute this from within the notebook and let me know the output just to be sure:

```
import sys
print(sys.version)
print(sys.version_info)
```
I cannot reproduce your second error and it is an error that does not seem to depend on your specific dataset. One more thing that would be helpful: Can you add the following lines below line 912 in `ssd_box_encode_decode_utils` (i.e. in `encode_y()` below the call to `generate_encode_template()`:

```
print("y_encode_template:", y_encode_template)
print("type(y_encode_template):", type(y_encode_template))
print("type(y_encode_template[0]):", type(y_encode_template[0]))
```

**Comment by vinodrajendran001** [comment]
3.5.4 |Anaconda, Inc.| (default, Sep 30 2017, 11:07:29) [MSC v.1900 64 bit (AMD64)]
sys.version_info(major=3, minor=5, micro=4, releaselevel='final', serial=0)

**Comment by vinodrajendran001** [comment]
3.5.4 |Anaconda, Inc.| (default, Sep 30 2017, 11:07:29) [MSC v.1900 64 bit (AMD64)]
sys.version_info(major=3, minor=5, micro=4, releaselevel='final', serial=0)

The second set of print statements doesn't seem to print anything

```
        # 1: Generate the template for y_encoded
        y_encode_template = self.generate_encode_template(batch_size=len(ground_truth_labels), diagnostics=True)
        y_encoded = np.copy(y_encode_template) # We'll write the ground truth box data to this array
        print("y_encode_template:", y_encode_template)
        print("type(y_encode_template):", type(y_encode_template))
        print("type(y_encode_template[0]):", type(y_encode_template[0]))
```

Error:

```
Epoch 1/10
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Users\Vinod\AppData\Local\conda\conda\envs\tensorflow-gpu\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\Vinod\AppData\Local\conda\conda\envs\tensorflow-gpu\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Vinod\AppData\Local\conda\conda\envs\tensorflow-gpu\lib\site-packages\keras\utils\data_utils.py", line 560, in data_generator_task
    generator_output = next(self._generator)
StopIteration

---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
<ipython-input-14-c11959bac2a8> in <module>()
     21                                                              cooldown=0)],
     22                               validation_data = val_generator,
---> 23                               validation_steps = ceil(n_val_samples/batch_size))
     24 
     25 

~\AppData\Local\conda\conda\envs\tensorflow-gpu\lib\site-packages\keras\legacy\interfaces.py in wrapper(*args, **kwargs)
     85                 warnings.warn('Update your `' + object_name +
     86                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 87             return func(*args, **kwargs)
     88         wrapper._original_function = func
     89         return wrapper

~\AppData\Local\conda\conda\envs\tensorflow-gpu\lib\site-packages\keras\engine\training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, initial_epoch)
   1807                 batch_index = 0
   1808                 while steps_done < steps_per_epoch:
-> 1809                     generator_output = next(output_generator)
   1810 
   1811                     if not hasattr(generator_output, '__len__'):

StopIteration: 
```

And also note that I am training this model from scratch not using any pre-trained weights.

**Comment by vinodrajendran001** [comment]
3.5.4 |Anaconda, Inc.| (default, Sep 30 2017, 11:07:29) [MSC v.1900 64 bit (AMD64)]
sys.version_info(major=3, minor=5, micro=4, releaselevel='final', serial=0)

The second set of print statements

```
y_encode_template: (array([[[ 0.,  0.,  0., ...,  1.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        ..., 
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.]],

       [[ 0.,  0.,  0., ...,  1.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        ..., 
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.]],

       [[ 0.,  0.,  0., ...,  1.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        ..., 
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.]],

       ..., 
       [[ 0.,  0.,  0., ...,  1.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        ..., 
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.]],

       [[ 0.,  0.,  0., ...,  1.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        ..., 
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.]],

       [[ 0.,  0.,  0., ...,  1.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        ..., 
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.]]]), [(array([   4.16,   12.48,   20.8 ,   29.12,   37.44,   45.76,   54.08,
         62.4 ,   70.72,   79.04,   87.36,   95.68,  104.  ,  112.32,
        120.64,  128.96,  137.28,  145.6 ,  153.92,  162.24,  170.56,
        178.88,  187.2 ,  195.52,  203.84,  212.16,  220.48,  228.8 ,
        237.12,  245.44,  253.76,  262.08,  270.4 ,  278.72,  287.04,
        295.36,  303.68,  312.  ,  320.32,  328.64,  336.96,  345.28,
        353.6 ,  361.92,  370.24,  378.56,  386.88,  395.2 ,  403.52,
        411.84]), array([   4.16,   12.48,   20.8 ,   29.12,   37.44,   45.76,   54.08,
         62.4 ,   70.72,   79.04,   87.36,   95.68,  104.  ,  112.32,
        120.64,  128.96,  137.28,  145.6 ,  153.92,  162.24,  170.56,
        178.88,  187.2 ,  195.52,  203.84,  212.16,  220.48,  228.8 ,
        237.12,  245.44,  253.76,  262.08,  270.4 ,  278.72,  287.04,
        295.36,  303.68,  312.  ,  320.32,  328.64,  336.96,  345.28,
        353.6 ,  361.92,  370.24,  378.56,  386.88,  395.2 ,  403.52,
        411.84])), (array([   8.66666667,   26.        ,   43.33333333,   60.66666667,
         78.        ,   95.33333333,  112.66666667,  130.        ,
        147.33333333,  164.66666667,  182.        ,  199.33333333,
        216.66666667,  234.        ,  251.33333333,  268.66666667,
        286.        ,  303.33333333,  320.66666667,  338.        ,
        355.33333333,  372.66666667,  390.        ,  407.33333333]), array([   8.66666667,   26.        ,   43.33333333,   60.66666667,
         78.        ,   95.33333333,  112.66666667,  130.        ,
        147.33333333,  164.66666667,  182.        ,  199.33333333,
        216.66666667,  234.        ,  251.33333333,  268.66666667,
        286.        ,  303.33333333,  320.66666667,  338.        ,
        355.33333333,  372.66666667,  390.        ,  407.33333333])), (array([  18.90909091,   56.72727273,   94.54545455,  132.36363636,
        170.18181818,  208.        ,  245.81818182,  283.63636364,
        321.45454545,  359.27272727,  397.09090909]), array([  18.90909091,   56.72727273,   94.54545455,  132.36363636,
        170.18181818,  208.        ,  245.81818182,  283.63636364,
        321.45454545,  359.27272727,  397.09090909])), (array([  52.,  156.,  260.,  364.]), array([  52.,  156.,  260.,  364.]))], [array([[ 29.4156421 ,  58.83128419],
       [ 41.6       ,  41.6       ],
       [ 72.05331359,  72.05331359],
       [ 58.83128419,  29.4156421 ]]), array([[  88.24692629,  176.49385258],
       [ 124.8       ,  124.8       ],
       [ 161.1161072 ,  161.1161072 ],
       [ 176.49385258,   88.24692629]]), array([[ 147.07821049,  294.15642097],
       [ 208.        ,  208.        ],
       [ 246.10891898,  246.10891898],
       [ 294.15642097,  147.07821049]]), array([[ 205.90949468,  411.81898936],
       [ 291.2       ,  291.2       ],
       [ 330.18976362,  330.18976362],
       [ 411.81898936,  205.90949468]])], [(8.3200000000000003, 8.3200000000000003), (17.333333333333332, 17.333333333333332), (37.81818181818182, 37.81818181818182), (104.0, 104.0)], [(0.5, 0.5), (0.5, 0.5), (0.5, 0.5), (0.5, 0.5)])
type(y_encode_template): <class 'tuple'>
type(y_encode_template[0]): <class 'numpy.ndarray'>
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-20-7949424aa2ad> in <module>()
----> 1 print (next(train_generator))

~\Downloads\OCR\ssd_keras\ssd_batch_generator.py in generate(self, batch_size, shuffle, train, ssd_box_encoder, returns, convert_to_3_channels, equalize, brightness, flip, translate, scale, max_crop_and_resize, random_pad_and_resize, random_crop, crop, resize, gray, limit_boxes, include_thresh, subtract_mean, divide_by_stddev, swap_channels, keep_images_without_gt)
   1209                     batch_y_true, batch_matched_anchors = ssd_box_encoder.encode_y(batch_y, diagnostics=True) # Encode the labels into the `y_true` tensor that the SSD loss function needs.
   1210                 else:
-> 1211                     batch_y_true = ssd_box_encoder.encode_y(batch_y, diagnostics=False) # Encode the labels into the `y_true` tensor that the SSD loss function needs.
   1212 
   1213             # Compile the output.

~\Downloads\OCR\ssd_keras\ssd_box_encode_decode_utils.py in encode_y(self, ground_truth_labels, diagnostics)
    921         class_vector = np.eye(self.n_classes) # An identity matrix that we'll use as one-hot class vectors
    922 
--> 923         for i in range(y_encode_template.shape[0]): # For each batch item...
    924             available_boxes = np.ones((y_encode_template.shape[1])) # 1 for all anchor boxes that are not yet matched to a ground truth box, 0 otherwise
    925             negative_boxes = np.ones((y_encode_template.shape[1])) # 1 for all negative boxes, 0 otherwise

AttributeError: 'tuple' object has no attribute 'shape'
```

And also note that I am training this model from scratch not using any pre-trained weights.

**Comment by pierluigiferrari** [comment]
The problem is that you set `diagnostics = True` in line 911 of `ssd_box_encode_decode_utils.py`, so you caused this error yourself. It must be `diagnostics = False`.

**Comment by vinodrajendran001** [comment]
Correct. 

Unfortunately, this also throws error in last batch of first epoch.

```
21/22 [===========================>..] - ETA: 2s - loss: 17.8976y_encode_template: [[[ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  ..., 
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]]

 [[ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  ..., 
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]]

 [[ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  ..., 
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]]

 ..., 
 [[ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  ..., 
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]]

 [[ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  ..., 
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]]

 [[ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  ..., 
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]]]
type(y_encode_template): <class 'numpy.ndarray'>
type(y_encode_template[0]): <class 'numpy.ndarray'>
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\Vinod\AppData\Local\conda\conda\envs\tensorflow-gpu\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\Vinod\AppData\Local\conda\conda\envs\tensorflow-gpu\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Vinod\AppData\Local\conda\conda\envs\tensorflow-gpu\lib\site-packages\keras\utils\data_utils.py", line 560, in data_generator_task
    generator_output = next(self._generator)
  File "C:\Users\Vinod\Downloads\OCR\ssd_keras\ssd_batch_generator.py", line 880, in generate
    if p >= (1-brightness[2]):
TypeError: 'bool' object is not subscriptable

y_encode_template: [[[ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  ..., 
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]]

 [[ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  ..., 
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]]

 [[ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  ..., 
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]]

 ..., 
 [[ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  ..., 
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]]

 [[ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  ..., 
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]]

 [[ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  ..., 
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]
  [ 0.  0.  0. ...,  1.  1.  1.]]]
type(y_encode_template): <class 'numpy.ndarray'>
type(y_encode_template[0]): <class 'numpy.ndarray'>
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
<ipython-input-14-c11959bac2a8> in <module>()
     21                                                              cooldown=0)],
     22                               validation_data = val_generator,
---> 23                               validation_steps = ceil(n_val_samples/batch_size))
     24 
     25 

~\AppData\Local\conda\conda\envs\tensorflow-gpu\lib\site-packages\keras\legacy\interfaces.py in wrapper(*args, **kwargs)
     85                 warnings.warn('Update your `' + object_name +
     86                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 87             return func(*args, **kwargs)
     88         wrapper._original_function = func
     89         return wrapper

~\AppData\Local\conda\conda\envs\tensorflow-gpu\lib\site-packages\keras\engine\training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, initial_epoch)
   1860                                 max_queue_size=max_queue_size,
   1861                                 workers=workers,
-> 1862                                 use_multiprocessing=use_multiprocessing)
   1863                         else:
   1864                             # No need for try/except because

~\AppData\Local\conda\conda\envs\tensorflow-gpu\lib\site-packages\keras\legacy\interfaces.py in wrapper(*args, **kwargs)
     85                 warnings.warn('Update your `' + object_name +
     86                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 87             return func(*args, **kwargs)
     88         wrapper._original_function = func
     89         return wrapper

~\AppData\Local\conda\conda\envs\tensorflow-gpu\lib\site-packages\keras\engine\training.py in evaluate_generator(self, generator, steps, max_queue_size, workers, use_multiprocessing)
   1953 
   1954             while steps_done < steps:
-> 1955                 generator_output = next(output_generator)
   1956                 if not hasattr(generator_output, '__len__'):
   1957                     raise ValueError('Output of generator should be a tuple '

StopIteration: 
```

**Comment by pierluigiferrari** [comment]
That's because you passed `True` for the `brightness` argument in `valid_dataset.generate()`. This argument expects a 3-tuple, not a boolean.

**Comment by vinodrajendran001** [comment]
yes i was about to say that.

Now the training is working..

Thanks for the prompt support.

Cheers,
Vinod
