### ISSUE TITLE
TypeError: Expected float for argument 'iou_threshold' not <tf.Tensor 'iou_threshold:0' shape=() dtype=float32> when Inference / Prediction on SSD300

### ISSUE THREAD

**Issue by humayun** [pierluigiferrari/ssd_keras#78]
Thank you for sharing the code of SSD. 

I am following note book for inference.

https://github.com/pierluigiferrari/ssd_keras/blob/master/ssd300_inference.ipynb

I just copied and paste first three block of code and got error.
Here is last code that I run:

```
K.clear_session() # Clear previous models from memory.

model = ssd_300(image_size=(img_height, img_width, 3),
                n_classes=20,
                mode='inference',
                l2_regularization=0.0005,
                scales=[0.1, 0.2, 0.37, 0.54, 0.71, 0.88, 1.05], # The scales for MS COCO are [0.07, 0.15, 0.33, 0.51, 0.69, 0.87, 1.05]
                aspect_ratios_per_layer=[[1.0, 2.0, 0.5],
                                         [1.0, 2.0, 0.5, 3.0, 1.0/3.0],
                                         [1.0, 2.0, 0.5, 3.0, 1.0/3.0],
                                         [1.0, 2.0, 0.5, 3.0, 1.0/3.0],
                                         [1.0, 2.0, 0.5],
                                         [1.0, 2.0, 0.5]],
                two_boxes_for_ar1=True,
                steps=[8, 16, 32, 64, 100, 300],
                offsets=[0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
                limit_boxes=False,
                variances=[0.1, 0.1, 0.2, 0.2],
                coords='centroids',
                normalize_coords=True,
                subtract_mean=[123, 117, 104],
                swap_channels=True,
                confidence_thresh=0.5,
                iou_threshold=0.45,
                top_k=200,
                nms_max_output_size=400)


```
Here is Error Message:

```
Traceback (most recent call last):
  File "/Users/hirshad/anaconda3/envs/keras_p3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-1e0465b87d7a>", line 28, in <module>
    nms_max_output_size=400)
  File "/Users/hirshad/Documents/ParkingSign/SSD_Keras_ParkingSign/models/keras_ssd300.py", line 427, in ssd_300
    name='decoded_predictions')(predictions)
  File "/Users/hirshad/anaconda3/envs/keras_p3/lib/python3.6/site-packages/keras/engine/topology.py", line 602, in __call__
    output = self.call(inputs, **kwargs)
  File "/Users/hirshad/Documents/ParkingSign/SSD_Keras_ParkingSign/keras_layers/keras_layer_DecodeDetections.py", line 264, in call
    name='loop_over_batch')
  File "/Users/hirshad/anaconda3/envs/keras_p3/lib/python3.6/site-packages/tensorflow/python/ops/functional_ops.py", line 389, in map_fn
    swap_memory=swap_memory)
  File "/Users/hirshad/anaconda3/envs/keras_p3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2623, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/Users/hirshad/anaconda3/envs/keras_p3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2456, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/Users/hirshad/anaconda3/envs/keras_p3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2406, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/Users/hirshad/anaconda3/envs/keras_p3/lib/python3.6/site-packages/tensorflow/python/ops/functional_ops.py", line 379, in compute
    packed_fn_values = fn(packed_values)
  File "/Users/hirshad/Documents/ParkingSign/SSD_Keras_ParkingSign/keras_layers/keras_layer_DecodeDetections.py", line 257, in <lambda>
    output_tensor = tf.map_fn(fn=lambda x: filter_predictions(x),
  File "/Users/hirshad/Documents/ParkingSign/SSD_Keras_ParkingSign/keras_layers/keras_layer_DecodeDetections.py", line 227, in filter_predictions
    name='loop_over_classes')
  File "/Users/hirshad/anaconda3/envs/keras_p3/lib/python3.6/site-packages/tensorflow/python/ops/functional_ops.py", line 389, in map_fn
    swap_memory=swap_memory)
  File "/Users/hirshad/anaconda3/envs/keras_p3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2623, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/Users/hirshad/anaconda3/envs/keras_p3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2456, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/Users/hirshad/anaconda3/envs/keras_p3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2406, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/Users/hirshad/anaconda3/envs/keras_p3/lib/python3.6/site-packages/tensorflow/python/ops/functional_ops.py", line 379, in compute
    packed_fn_values = fn(packed_values)
  File "/Users/hirshad/Documents/ParkingSign/SSD_Keras_ParkingSign/keras_layers/keras_layer_DecodeDetections.py", line 220, in <lambda>
    filtered_single_classes = tf.map_fn(fn=lambda i: filter_single_class(i),
  File "/Users/hirshad/Documents/ParkingSign/SSD_Keras_ParkingSign/keras_layers/keras_layer_DecodeDetections.py", line 209, in filter_single_class
    single_class_nms = tf.cond(tf.equal(tf.size(single_class), 0), no_confident_predictions, perform_nms)
  File "/Users/hirshad/anaconda3/envs/keras_p3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1748, in cond
    _, res_f = context_f.BuildCondBranch(fn2)
  File "/Users/hirshad/anaconda3/envs/keras_p3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1642, in BuildCondBranch
    r = fn()
  File "/Users/hirshad/Documents/ParkingSign/SSD_Keras_ParkingSign/keras_layers/keras_layer_DecodeDetections.py", line 200, in perform_nms
    name='non_maximum_suppresion')
  File "/Users/hirshad/anaconda3/envs/keras_p3/lib/python3.6/site-packages/tensorflow/python/ops/gen_image_ops.py", line 649, in non_max_suppression
    iou_threshold=iou_threshold, name=name)
  File "/Users/hirshad/anaconda3/envs/keras_p3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 693, in apply_op
    attr_value.f = _MakeFloat(value, key)
  File "/Users/hirshad/anaconda3/envs/keras_p3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 144, in _MakeFloat
    (arg_name, repr(v)))
TypeError: Expected float for argument 'iou_threshold' not <tf.Tensor 'iou_threshold:0' shape=() dtype=float32>.

```

**Comment by pierluigiferrari** [comment]
What TensorFlow version are you on? I can't reproduce this error in v1.4.1.

**Comment by humayun** [comment]
thank you for suggestion. I will follow in future. 

I am using tensorflow 1.1.0 installed in conda environment.

Best.

**Comment by pierluigiferrari** [comment]
I've just pushed a fix. Pull the latest master and let me know if the error persists.

**Comment by humayun** [comment]
Thanks Pierluigiferrari. It is working but give low accuracy for Parking Sign Detection. 

I am fine-tuning the model (VGG_ILSVRC_16_layers_fc_reduced.h5) with my dataset, which consisted of 500 images of parking sign (Single Class problem). The image size is 1050 x 1050 pixels. Parking Sign in the images are mostly square or few cases rectangle. Max aspect ratio. 2:1 or 1:2. As there is only one class which is parking sign in street view images, I selected n_classes = 2 {Background, Parking Sign}.
Initially, I fine-tune the ssd300 model with default setting/parameters. Model stoped training after 8 Epoch due to not decreasing in val_loss (~5.88), almost same number for training loss. This trained model gave poor detection of parking sign.
What is your expert opinion to fine-tune the existing model with parameters (Aspect Ratio, scales, steps, offsets, variances).

Thank you.

Best,
-Humayun

**Comment by pierluigiferrari** [comment]
8 epochs at 500 images is nothing. I'm not sure why the loss won't decrease after that, but you should have to train much, much longer than that before you get decent predictions. Remove the early stopping call back so that it doesn't get in the way. Train for longer and see what happens. Also, on an unrelated note, try to use data augmentation more aggressively since your dataset is very small. Also, note that it should be `n_classes = 1` since the background class is counted automatically, but the fact that you set it to 2 didn't matter in your training. You don't need to change anything about the aspect ratios. Whether it would make sense to change the scaling factors depends on how large your objects are relative to the image size. The scaling factors should cover that range.
