### ISSUE TITLE
SSD7 saving and loading weights error

### ISSUE THREAD

**Issue by gnujosh** [pierluigiferrari/ssd_keras#90]
Thanks for making this available, I particularly appreciate the easy to use data generation augmentation facilities for scaling, cropping, resizing, etc.

I've just followed the ssd7_training jupyter notebook for setting up a fast-training SSD, and after completing a training run, I simply try to save the model weights and then reload them:
```
>>> model.save('trained-model.h5')
>>> model2 = load_model('trained-model.h5', custom_objects={'AnchorBoxes':AnchorBoxes, 
                                                            'compute_loss':ssd_loss.compute_loss})
```
But, model.load_weights does work.

I get the following error message when trying to load:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/josh.robinson/anaconda3/lib/python3.6/site-packages/keras/models.py", line 274, in load_model
    sample_weight_mode=sample_weight_mode)
  File "/home/josh.robinson/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 830, in compile
    sample_weight, mask)
  File "/home/josh.robinson/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 429, in weighted
    score_array = fn(y_true, y_pred)
  File "/home/josh.robinson/ssd_keras-master/keras_loss_function/keras_ssd_loss.py", line 125, in compute_loss
    self.neg_pos_ratio = tf.constant(self.neg_pos_ratio)
  File "/home/josh.robinson/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/josh.robinson/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 374, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/home/josh.robinson/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 299, in _AssertCompatible
    raise TypeError("List of Tensors when single Tensor expected")
TypeError: List of Tensors when single Tensor expected
```

Any ideas?

**Comment by mke21** [comment]
It happens when you load the model for a second time. K.clear_session() doesn't seem to work with me. Restarting the kernel gives you another chance.

**Comment by hgasimov** [comment]
Agree with @mke21 . It also happens to me when I load the model second time.

**Comment by mraduldubey** [comment]
@mke21 @hgasimov What if you have to load two models at a time ?
